version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/tools/phan"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/php-cs-fixer"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/phpcs"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/phpmd"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/phpmnd"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/phpstan"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/tools/psalm"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
